// Generated by gencpp from file service_node/AddTwoInts.msg
// DO NOT EDIT!


#ifndef SERVICE_NODE_MESSAGE_ADDTWOINTS_H
#define SERVICE_NODE_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <service_node/AddTwoIntsRequest.h>
#include <service_node/AddTwoIntsResponse.h>


namespace service_node
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace service_node


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::service_node::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::service_node::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::service_node::AddTwoInts > {
  static const char* value()
  {
    return "service_node/AddTwoInts";
  }

  static const char* value(const ::service_node::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::service_node::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::service_node::AddTwoInts >
template<>
struct MD5Sum< ::service_node::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::service_node::AddTwoInts >::value();
  }
  static const char* value(const ::service_node::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::service_node::AddTwoIntsRequest> should match
// service_traits::DataType< ::service_node::AddTwoInts >
template<>
struct DataType< ::service_node::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::service_node::AddTwoInts >::value();
  }
  static const char* value(const ::service_node::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::service_node::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::service_node::AddTwoInts >
template<>
struct MD5Sum< ::service_node::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::service_node::AddTwoInts >::value();
  }
  static const char* value(const ::service_node::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::service_node::AddTwoIntsResponse> should match
// service_traits::DataType< ::service_node::AddTwoInts >
template<>
struct DataType< ::service_node::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::service_node::AddTwoInts >::value();
  }
  static const char* value(const ::service_node::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SERVICE_NODE_MESSAGE_ADDTWOINTS_H
